/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTransaction: typeof import('./src/components/AddTransaction.vue')['default']
    Balance: typeof import('./src/components/Balance.vue')['default']
    Form1: typeof import('./src/components/Form1.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IncomeExpenses: typeof import('./src/components/IncomeExpenses.vue')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    TransactionList: typeof import('./src/components/TransactionList.vue')['default']
  }
}
